(define-module (heart)
  #:use-module (model-viewer))

(define-public (heart)
  `(html (@ (lang "en"))
	 (head
	  (meta (@ (charset "utf-8")))
	  (title "Leo Almighty"))
	 (body
	  ,@(gen-model-viewer "heart.glb")
	  ;; (model-viewer (@ (ar)
	  ;;		   (alt "Leo Model")
	  ;;		   (src "./leo.glb")
	  ;;		   ;; (ios-src "./leo_texture.usdz")
	  ;;		   (style "width:480;height:720;")
	  ;;		   (shadow-intensity "1")
	  ;;		   (camera-controls)
	  ;;		   (touch-action "pan-y")
	  ;;		   (interaction-prompt "auto")
	  ;;		   (auto-rotate)
	  ;;		   (scale "1 1 1")
	  ;;		   (ar-modes "webxr scene-viewer quick-look")
	  ;;		   (magic-leap))
	  ;;		"")
	  ;; (script (@ (type "module")
	  ;;	     (src "./model-viewer.js"))
	  ;;	  "")
	  )))
