(define-module (mapping)
  #:use-module (artanis artanis)
  #:use-module (ice-9 textual-ports)
  #:use-module (main-page)
  #:use-module (leo)
  #:use-module (heart))

(define-public (start)
  (init-server #:statics '(css glb js usdz))
  (get "/" (lambda (rc)
	     (tpl->html (main-page))))
  (get "/leo" (lambda (rc) (tpl->html (leo-allmighty rc))))
  (get "/heart" (lambda (rc) (tpl->html (heart))))
  (run #:port 8080))
