(define-module (model-viewer))
(define-public (gen-model-viewer path)
  `((model-viewer (@ (ar)
		     (alt "Leo Model")
		     (src ,path)
		     ;; (ios-src "./leo_texture.usdz")
		     (style "width:720;height:480;")
		     (shadow-intensity "1")
		     (camera-controls)
		     (touch-action "pan-y")
		     (interaction-prompt "auto")
		     (auto-rotate)
		     (scale "1 1 1")
		     (ar-modes "webxr scene-viewer quick-look")
		     (magic-leap))
		  "")
    (script (@ (type "module")
	       (src "./model-viewer.js"))
	    "")))
